spring:
  datasource:
    url: jdbc:mysql://zhouym.icu:3306/fwwb?useUnicode=true&characterEncoding=utf-8
    username: fwwb
    password: fwwb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
server:
  port: 8083