spring:
  datasource:
    url: jdbc:mysql://zhouym.icu:3306/spring?useUnicode=true&characterEncoding=utf-8
    username: spring
    password: spring
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update